on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set-up Node.js
        uses: actions/setup-node@v1
      - run: npm install
      - name: 'Lint'
        run: npm run eslint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
        mongodb-version: [4.0, 4.2]
    steps:
      - uses: actions/checkout@v1
      - name: Set-up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set-up MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - name: 'Test'
        run: npm test


  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set-up Node.js
        uses: actions/setup-node@v1

      - name: Set-up MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.2'
      - run: npm install
      - name: 'Cover'
        run: npm run cover
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
